#!/usr/bin/env bash

BASEDIR=$(pwd)
EXE=$BASEDIR'/dist/enlighten'
TESTDIR=/tmp/enlighten_testing
export BACKLIGHT_SEARCH_PATH="$TESTDIR:/sys/class/backlight:/sys/class/leds"
export BACKLIGHT_DEVICE=dev4
declare -i TESTCOUNT
declare -i TESTSFAILED

# setup the test env
mkdir -p "$TESTDIR"/dev{1,2,3,4,5}
echo 0 > "$TESTDIR"/dev2/brightness
echo 1 > "$TESTDIR"/dev3/max_brightness
echo 250 > "$TESTDIR"/dev4/brightness
echo 1347 > "$TESTDIR"/dev4/max_brightness
mkdir -p "$TESTDIR"/dev5/{max_,}brightness
touch "$TESTDIR"/notdev

# helper functions
FAIL() {
    ((TESTCOUNT++))
    ((TESTSFAILED++))
    echo 'FAIL'
}

PASS() {
    ((TESTCOUNT++))
    echo 'PASS'
}

# non-brightness commands (device detection, help and version output)
LIST=$(eval "$EXE" l)
printf 'ignore non-directories: [ %s ]\n' $([[ "$LIST" =~ 'notdev' ]] && FAIL || PASS)
printf 'ignore empty directories: [ %s ]\n' $([[ "$LIST" =~ 'dev1' ]] && FAIL || PASS)
printf 'ignore directories without max_brightness: [ %s ]\n' $([[ "$LIST" =~ 'dev2' ]] && FAIL || PASS)
printf 'ignore directories without brightness: [ %s ]\n' $([[ "$LIST" =~ 'dev3' ]] && FAIL || PASS)
printf 'ignore directories whose brightness are not regular files: [ %s ]\n' $([[ "$LIST" =~ 'dev5' ]] && FAIL || PASS)
printf 'detect directories with both brightness files: [ %s ]\n' $([[ "$LIST" == *'dev4'* ]] && PASS || FAIL)

GET=$(eval "$EXE" h 2>&1)
printf 'properly gets help output: [ %s ]\n' $([[ "$GET" == 'Usage'* ]] && PASS || FAIL)

GET=$(eval "$EXE" v 2>&1)
printf 'properly gets version output: [ %s ]\n' $([[ "$GET" == $(git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g') ]] && PASS || FAIL)

# brightness fetching
GET=$(eval "$EXE")
printf 'properly fetches brightness: [ %s ]\n' $([[ "$GET" == '250 / 1347 (18%)' ]] && PASS || FAIL)

# brightness manipulation
eval "$EXE" 0
GET=$(eval "$EXE")
printf 'properly sets brightness: [ %s ]\n' $([[ "$GET" == '0 / 1347 (0%)' ]] && PASS || FAIL)

eval "$EXE" '+500'
GET=$(eval "$EXE")
printf 'properly increments brightness: [ %s ]\n' $([[ "$GET" == '500 / 1347 (37%)' ]] && PASS || FAIL)

eval "$EXE" '-100'
GET=$(eval "$EXE")
printf 'properly decrements brightness: [ %s ]\n' $([[ "$GET" == '400 / 1347 (29%)' ]] && PASS || FAIL)

eval "$EXE" '50%'
GET=$(eval "$EXE")
printf 'properly sets brightness by percent: [ %s ]\n' $([[ "$GET" == '673 / 1347 (49%)' ]] && PASS || FAIL)

eval "$EXE" '+7%'
GET=$(eval "$EXE")
printf 'properly increments brightness by percent: [ %s ]\n' $([[ "$GET" == '767 / 1347 (56%)' ]] && PASS || FAIL)

eval "$EXE" '-12%'
GET=$(eval "$EXE")
printf 'properly decrements brightness by percent: [ %s ]\n' $([[ "$GET" == '606 / 1347 (44%)' ]] && PASS || FAIL)

# thresholds
export BACKLIGHT_THRESHOLD_MIN='1'
export BACKLIGHT_THRESHOLD_MAX='25%'
eval "$EXE" '75%'
GET=$(eval "$EXE")
printf 'respects threshold maximum: [ %s ]\n' $([[ "$GET" == '336 / 1347 (24%)' ]] && PASS || FAIL)

eval "$EXE" '0'
GET=$(eval "$EXE")
printf 'respects threshold minimum: [ %s ]\n' $([[ "$GET" == '1 / 1347 (0%)' ]] && PASS || FAIL)
unset BACKLIGHT_THRESHOLD_MIN
unset BACKLIGHT_THRESHOLD_MAX

# garbage input
eval "$EXE" 0 # reset
GET=$(eval "$EXE")

eval "$EXE" '+pants' &> /dev/null
GET=$(eval "$EXE")
printf 'ignores basic garbage input: [ %s ]\n' $([[ "$GET" == '0 / 1347 (0%)' ]] && PASS || FAIL)

# garbage environment
export BACKLIGHT_SEARCH_PATH="$TESTDIR:/sys/class/backlight:/sys/class/leds:"
GET=$(eval "$EXE")
printf 'ignores empty paths in SEARCH_PATH: [ %s ]\n' $([[ "$GET" == '0 / 1347 (0%)' ]] && PASS || FAIL)

export BACKLIGHT_DEVICE=nonexistant
GET=$(eval "$EXE" 2>&1)
printf 'errors on basic garbage device name: [ %s ]\n' $([[ "$GET" =~ "Failed to find a match for the specified device" ]] && PASS || FAIL)

# summary
#printf '\n%d of %d tests failed\n' "$TESTSFAILED" "$TESTCOUNT"

rm -r "$TESTDIR"
